## Pandas - Join/merge

Le join si effettuano con il metodo merge

In [1]:
import pandas as pd

In [2]:
#creo un dict con due voci:
data = {'codice':range(1001, 1006), 'nome':['mela', 'pera', 'banana', 'kiwi', 'fragola']}
df_prodotti = pd.DataFrame(data)
df_prodotti

   codice     nome
0    1001     mela
1    1002     pera
2    1003   banana
3    1004     kiwi
4    1005  fragola

In [3]:
#creo una seconda tabella con le qta
data = {'codice':range(1001, 1011), 'qta':[10,20,30,40,50,60,70,80,90,99]}
df_magazzino = pd.DataFrame(data)
df_magazzino

   codice  qta
0    1001   10
1    1002   20
2    1003   30
3    1004   40
4    1005   50
5    1006   60
6    1007   70
7    1008   80
8    1009   90
9    1010   99

In [4]:
df1 = pd.merge(df_prodotti, df_magazzino, on='codice', how='left')
df1

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003   banana   30
3    1004     kiwi   40
4    1005  fragola   50

In [5]:
df2 = pd.merge(df_prodotti, df_magazzino, on='codice', how='right')
df2

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003   banana   30
3    1004     kiwi   40
4    1005  fragola   50
5    1006      NaN   60
6    1007      NaN   70
7    1008      NaN   80
8    1009      NaN   90
9    1010      NaN   99

In [6]:
#aggiungo una riga a df_prodotti
df_prodotti.loc[5] = {"codice":1100, "nome":"fichi"}
df_prodotti

   codice     nome
0    1001     mela
1    1002     pera
2    1003   banana
3    1004     kiwi
4    1005  fragola
5    1100    fichi

In [7]:
df2 = pd.merge(df_prodotti, df_magazzino, on='codice', how='right')
df2

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003   banana   30
3    1004     kiwi   40
4    1005  fragola   50
5    1006      NaN   60
6    1007      NaN   70
7    1008      NaN   80
8    1009      NaN   90
9    1010      NaN   99

In [8]:
df2 = pd.merge(df_prodotti, df_magazzino, on='codice', how='inner')
df2

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003   banana   30
3    1004     kiwi   40
4    1005  fragola   50

In [9]:
df2 = pd.merge(df_prodotti, df_magazzino, on='codice', how='outer')
df2

    codice     nome   qta
0     1001     mela  10.0
1     1002     pera  20.0
2     1003   banana  30.0
3     1004     kiwi  40.0
4     1005  fragola  50.0
5     1006      NaN  60.0
6     1007      NaN  70.0
7     1008      NaN  80.0
8     1009      NaN  90.0
9     1010      NaN  99.0
10    1100    fichi   NaN

## Concat
Serve per unire due dataframe con struttura compatibile (ugual numero e nome di colonne)

In [10]:
data = {'codice':[10,20,30],
        'nome':['kiwi','mela','pera'],
        'qta':[100, 67, 34]}
dfa = pd.DataFrame(data)
dfa

   codice  nome  qta
0      10  kiwi  100
1      20  mela   67
2      30  pera   34

In [11]:
data = {'codice':[100,120],
        'nome':['patate','carote'],
        'qta':[22,33]}
dfb = pd.DataFrame(data)
dfb

   codice    nome  qta
0     100  patate   22
1     120  carote   33

In [14]:
dfc = pd.concat([dfa, dfb], ignore_index=True)
dfc

   codice    nome  qta
0      10    kiwi  100
1      20    mela   67
2      30    pera   34
3     100  patate   22
4     120  carote   33

caso in cui unisco 2 tabelle e rigenero l'indice in seguito

In [15]:
dfd = pd.concat([dfa, dfb])
dfd

   codice    nome  qta
0      10    kiwi  100
1      20    mela   67
2      30    pera   34
0     100  patate   22
1     120  carote   33

In [17]:
#rigenero l'indice
dfd.reset_index(drop=True, inplace=True)
dfd

   codice    nome  qta
0      10    kiwi  100
1      20    mela   67
2      30    pera   34
3     100  patate   22
4     120  carote   33

## Raggruppamenti - GroupBy

In [18]:
data = {
    'codice':range(1001, 1006), 
    'nome':['mela', 'pera', 'banana', 'kiwi', 'fragola'],
    'qta':[12,23,34,45,56],
    'id_mag':[1,0,1,1,0]
}
dfp = pd.DataFrame(data)
dfp

   codice     nome  qta  id_mag
0    1001     mela   12       1
1    1002     pera   23       0
2    1003   banana   34       1
3    1004     kiwi   45       1
4    1005  fragola   56       0

In [20]:
dfp.groupby("id_mag").groups

{0: [1, 4], 1: [0, 2, 3]}

In [21]:
dfp.groupby("id_mag").get_group(0)

   codice     nome  qta  id_mag
1    1002     pera   23       0
4    1005  fragola   56       0

In [22]:
dfp.groupby("id_mag").get_group(1)

   codice    nome  qta  id_mag
0    1001    mela   12       1
2    1003  banana   34       1
3    1004    kiwi   45       1

In [23]:
dfp.groupby("id_mag")['qta'].sum()

id_mag
0    79
1    91
Name: qta, dtype: int64

In [26]:
dfp.groupby("id_mag")["qta"].describe()

        count       mean        std   min    25%   50%    75%   max
id_mag
0         2.0  39.500000  23.334524  23.0  31.25  39.5  47.75  56.0
1         3.0  30.333333  16.802778  12.0  23.00  34.0  39.50  45.0