### Report vendite
Analisi con pandas

In [1]:
import pandas as pd

Ho 4 file. 
* customer
* prodotti
* transazioni
* storico transazioni

1. Quali sono i 10 prodotti più redditizi?

In [6]:
dfcu = pd.read_csv("T02-eCommerce-CustomerMD.csv", delimiter=";")
dfcu.head()

   Customer_ID         Country
0        12346  United Kingdom
1        12347         Iceland
2        12348         Finland
3        12349           Italy
4        12350          Norway

In [7]:
dfcu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5856 entries, 0 to 5855
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5856 non-null   int64
 1   Country      5856 non-null   object
dtypes: int64(1), object(1)
memory usage: 91.6+ KB

In [8]:
dfcu.describe()

        Customer_ID
count   5856.000000
mean   15318.908470
std     1715.858912
min    12346.000000
25%    13834.750000
50%    15322.500000
75%    16808.250000
max    18287.000000

**Prodotti**

In [12]:
dfpr = pd.read_csv("T02-eCommerce-ProductMD.csv", delimiter=",", encoding="latin-1")
dfpr.head()

  StockCode              Description    Category         Subcategory
0    10002R    ROBOT PENCIL SHARPNER  Stationery  Desktop Stationery
1     10109     BENDY COLOUR PENCILS  Stationery  Desktop Stationery
2     10120             DOGGY RUBBER  Stationery  Desktop Stationery
3    10123C    HEARTS WRAPPING TAPE   Stationery  Desktop Stationery
4    10123G  ARMY CAMO WRAPPING TAPE  Stationery  Desktop Stationery

**Transazioni**

In [14]:
dftr = pd.read_excel("T02-eCommerce-TransactionsL3M.xlsx", engine="openpyxl")
dftr.head()

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Invoice StockCode  Quantity  Price  Customer_ID       Invoice_time
0  565080     20677         8   1.25        13509  D01/9/19T08:25:00
1  565080     22128        24   1.25        13509  D01/9/19T08:25:00
2  565082     22423         2  12.75        13305  D01/9/19T09:15:00
3  565082    15060B         8   3.75        13305  D01/9/19T09:15:00
4  565082     23245         4   4.95        13305  D01/9/19T09:15:00

In [15]:
dftr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130287 entries, 0 to 130286
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       130287 non-null  object
 1   StockCode     130287 non-null  object
 2   Quantity      130287 non-null  int64
 3   Price         130287 non-null  float64
 4   Customer_ID   130287 non-null  int64
 5   Invoice_time  130287 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 6.0+ MB

Dati storici delle transazioni

In [17]:
dftrh = pd.read_excel("T02-eCommerce-TransactionsHistory.xlsx", engine="openpyxl")
dftrh.head()

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Invoice StockCode  Quantity  Price  Customer_ID        Invoice_time
0  489434     85048        12   6.95        13085  D01/12/17T07:45:00
1  489434    79323P        12   6.75        13085  D01/12/17T07:45:00
2  489434    79323W        12   6.75        13085  D01/12/17T07:45:00
3  489434     22041        48   2.10        13085  D01/12/17T07:45:00
4  489434     21232        24   1.25        13085  D01/12/17T07:45:00

In [18]:
dftrh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545592 entries, 0 to 545591
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Invoice       545592 non-null  object
 1   StockCode     545592 non-null  object
 2   Quantity      545592 non-null  int64
 3   Price         545592 non-null  float64
 4   Customer_ID   545592 non-null  int64
 5   Invoice_time  545592 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 25.0+ MB

unisco le due tabelle con le transazioni

In [19]:
df_tot = pd.concat([dftr, dftrh], ignore_index=True, sort=False)
df_tot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1091184 entries, 0 to 1091183
Data columns (total 6 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Invoice       1091184 non-null  object
 1   StockCode     1091184 non-null  object
 2   Quantity      1091184 non-null  int64
 3   Price         1091184 non-null  float64
 4   Customer_ID   1091184 non-null  int64
 5   Invoice_time  1091184 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 50.0+ MB

In [20]:
df_tot.head()

  Invoice StockCode  Quantity  Price  Customer_ID        Invoice_time
0  489434     85048        12   6.95        13085  D01/12/17T07:45:00
1  489434    79323P        12   6.75        13085  D01/12/17T07:45:00
2  489434    79323W        12   6.75        13085  D01/12/17T07:45:00
3  489434     22041        48   2.10        13085  D01/12/17T07:45:00
4  489434     21232        24   1.25        13085  D01/12/17T07:45:00

Join delle due tabelle: transaction e customer

In [23]:
customer = dfcu
product = dfpr
transactions = df_tot

transaction2 = transactions.merge(
    customer,
    on="Customer_ID",
    how="left"
)

transaction2.head()

,Invoice,StockCode,Quantity,Price,Customer_ID,Invoice_time,Country
0,489434,85048,12,6.95,13085,D01/12/17T07:45:00,United Kingdom
1,489434,79323P,12,6.75,13085,D01/12/17T07:45:00,United Kingdom
2,489434,79323W,12,6.75,13085,D01/12/17T07:45:00,United Kingdom
3,489434,22041,48,2.10,13085,D01/12/17T07:45:00,United Kingdom
4,489434,21232,24,1.25,13085,D01/12/17T07:45:00,United Kingdom

Per trovare quali sono i 10 prodotti più redditizi:

* calcolare il valore venduto per riga
* raggruppare per prodotto
* sommare

In [24]:
transaction2["total_row"] = transaction2["Quantity"] * transaction2["Price"]
transaction2.head()

,Invoice,StockCode,Quantity,Price,Customer_ID,Invoice_time,Country,total_row
0,489434,85048,12,6.95,13085,D01/12/17T07:45:00,United Kingdom,83.4
1,489434,79323P,12,6.75,13085,D01/12/17T07:45:00,United Kingdom,81.0
2,489434,79323W,12,6.75,13085,D01/12/17T07:45:00,United Kingdom,81.0
3,489434,22041,48,2.10,13085,D01/12/17T07:45:00,United Kingdom,100.8
4,489434,21232,24,1.25,13085,D01/12/17T07:45:00,United Kingdom,30.0

totale per prodotto

In [ ]:
totale_prodotto = (
    transaction2.groupby("StockCode")["total_row"]
      .sum()
      .reset_index()
)
totale_prodotto.head()

  StockCode  total_row
0     10109       3.36
1     10120     234.78
2    10123C     433.64
3    10123G     181.88
4    10124A      48.72

In [32]:
totale_prodotto = totale_prodotto.sort_values(
    by="total_row",
    ascending=False
)
#limito il df ai soli 10 prodotti
totale_prodotto = totale_prodotto.head(10)
totale_prodotto.head(10)

     StockCode  total_row
1374     22423  471333.20
3005    85123A  431172.00
2989    85099B  278981.68
2824     84879  213835.42
2288     47566  184439.30
3406      POST  173051.98
2319     48138  114088.46
2991    85099F  112639.40
211      20685  111163.94
1426     22502  109103.90

faccio una join con la tabella dei prodotti per avere anche la descrizione

In [33]:
totale_prodotto_desc = totale_prodotto.merge(
    product,
    on="StockCode",
    how="left"
)

totale_prodotto_desc.head(10)

,StockCode,total_row,Description,Category,Subcategory
0,22423,471333.20,REGENCY CAKESTAND 3 TIER,Home,Kitchen
1,85123A,431172.00,WHITE HANGING HEART T-LIGHT HOLDER,Air fragances,Candles
2,85099B,278981.68,JUMBO BAG RED RETROSPOT,Accessories,Bags
3,84879,213835.42,ASSORTED COLOUR BIRD ORNAMENT,Home,Decoration
4,47566,184439.30,PARTY BUNTING,Kids,Party
5,POST,173051.98,POSTAGE,Others,Code
6,48138,114088.46,DOORMAT UNION FLAG,Home,Furniture
7,85099F,112639.40,JUMBO BAG STRAWBERRY,Accessories,Bags
8,20685,111163.94,DOORMAT RED RETROSPOT,Home,Furniture
9,22502,109103.90,PICNIC BASKET WICKER 60 PIECES,Hobbies,Garden

TODO:
- elimina colonne
- rinomina colonne
- fai un grafico