## Pulizia mailing list

In [1]:
import pandas as pd

df = pd.read_csv("../dataset/dati_mailing_list.csv", delimiter=",")
df.head()

,First name,Surname,__Email_Entered,Gender,Age,Logins,_CREDIT,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First name       20 non-null     object
 1   Surname          20 non-null     object
 2   __Email_Entered  20 non-null     object
 3   Gender           20 non-null     object
 4   Age              16 non-null     float64
 5   Logins           16 non-null     float64
 6   _CREDIT          20 non-null     float64
 7   IP_Address       20 non-null     object
dtypes: float64(3), object(5)
memory usage: 1.4+ KB

In [3]:
df.describe()

             Age     Logins     _CREDIT
count  16.000000  16.000000   20.000000
mean   43.375000   2.812500  104.281000
std    18.463929   1.424488  127.852396
min    19.000000   1.000000 -100.000000
25%    33.500000   1.750000   20.357500
50%    40.000000   3.000000   77.110000
75%    48.750000   3.250000  208.040000
max    79.000000   5.000000  362.200000

In [4]:
df.dtypes

First name          object
Surname             object
__Email_Entered     object
Gender              object
Age                float64
Logins             float64
_CREDIT            float64
IP_Address          object
dtype: object

In [5]:
#rename colonne
df.rename(columns={"__Email_Entered": "email"}, inplace=True)
df.rename(columns={"First name": "nome"}, inplace=True)
df.rename(columns={"_CREDIT": "credito"}, inplace=True)
df.rename(columns={"Surname": "cognome"}, inplace=True)
df.rename(columns={"Age": "eta"}, inplace=True)
df.rename(columns={"Gender": "genere"}, inplace=True)
df.head()

,nome,cognome,email,genere,eta,Logins,credito,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74

In [6]:
df2 = df[["nome", "cognome", "email", "eta", "genere", "credito"]].copy()
df2

,nome,cognome,email,eta,genere,credito
0,DIANA,Herries,sherries3@google.com.au,42.0,Female,58.00
1,Maira,Totaro,mtota21@salento.com,NaN,Female,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,36.0,Male,308.15
3,Ferenc,TOTH,toth.f@ucla.edu,NaN,Male,362.20
4,SONJA,VAN DEER,svdeer@indiatimes.com,37.0,Female,88.00
5,Carolina,DIAZ,c.diaz.12@elpais.com,38.0,Female,19.99
6,Ruby,Mammatt,rmammatt16@prweb,22.0,Rather not say,116.28
7,AKSHAY,BAKSHI,bakshi.a@unesco.org,79.0,Male,20.48
8,AKSHAY,BAKSHI,bakshi.a@unesco.org,79.0,Male,20.48
9,geraldine,lammas,glammas-11@fda.gov,NaN,Female,5.99
10,Jacek,WLOSKI,jacekwlochem.com,54.0,Male,207.27
11,Nichole,De Giovanni,ndegio@ifeng.com,21.0,Female,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
13,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
14,Daron,eagger,deagger1983@simpleme.org,38.0,Male,66.22
15,Liam,Pasley,lpasley26@usatoday.com,26.0,Male,138.58
16,rey,KEILLOH,rkeilloh27@unesco.org,NaN,Rather not say,210.35
17,Hans,Fischer,hansfish@hc360.com,19.0,Male,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,64.0,Female,-100.00
19,Nadine,De Smet,nadineds22@email.be,45.0,Female,4.38

In [7]:

df2["nome"] = df2["nome"].str.strip().str.title()
df2["cognome"] = df2["cognome"].str.strip().str.title()
df2

,nome,cognome,email,eta,genere,credito
0,Diana,Herries,sherries3@google.com.au,42.0,Female,58.00
1,Maira,Totaro,mtota21@salento.com,NaN,Female,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,36.0,Male,308.15
3,Ferenc,Toth,toth.f@ucla.edu,NaN,Male,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,37.0,Female,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,38.0,Female,19.99
6,Ruby,Mammatt,rmammatt16@prweb,22.0,Rather not say,116.28
7,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
8,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,NaN,Female,5.99
10,Jacek,Wloski,jacekwlochem.com,54.0,Male,207.27
11,Nichole,De Giovanni,ndegio@ifeng.com,21.0,Female,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
13,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
14,Daron,Eagger,deagger1983@simpleme.org,38.0,Male,66.22
15,Liam,Pasley,lpasley26@usatoday.com,26.0,Male,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,NaN,Rather not say,210.35
17,Hans,Fischer,hansfish@hc360.com,19.0,Male,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,64.0,Female,-100.00
19,Nadine,De Smet,nadineds22@email.be,45.0,Female,4.38

elimino le righe con email no valida

In [8]:
import re

email_regex = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"


.str.match(...) → verifica la regex

na=False → considera non valide le email NaN

il filtro elimina automaticamente le righe non valide

In [9]:
df3 = df2[df2["email"].str.match(email_regex, na=False)].copy()
df3

,nome,cognome,email,eta,genere,credito
0,Diana,Herries,sherries3@google.com.au,42.0,Female,58.00
1,Maira,Totaro,mtota21@salento.com,NaN,Female,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,36.0,Male,308.15
3,Ferenc,Toth,toth.f@ucla.edu,NaN,Male,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,37.0,Female,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,38.0,Female,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
8,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,NaN,Female,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,21.0,Female,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
13,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
14,Daron,Eagger,deagger1983@simpleme.org,38.0,Male,66.22
15,Liam,Pasley,lpasley26@usatoday.com,26.0,Male,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,NaN,Rather not say,210.35
17,Hans,Fischer,hansfish@hc360.com,19.0,Male,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,64.0,Female,-100.00
19,Nadine,De Smet,nadineds22@email.be,45.0,Female,4.38

elimno duplicati

In [10]:
#più colonne
#df = df.drop_duplicates(subset=["Nome", "email"])
#quale tengo...
#df = df.drop_duplicates(subset=["email"], keep="first")  # default
#df = df.drop_duplicates(subset=["email"], keep="last")

df4 = df3.drop_duplicates().copy()
df4

,nome,cognome,email,eta,genere,credito
0,Diana,Herries,sherries3@google.com.au,42.0,Female,58.00
1,Maira,Totaro,mtota21@salento.com,NaN,Female,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,36.0,Male,308.15
3,Ferenc,Toth,toth.f@ucla.edu,NaN,Male,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,37.0,Female,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,38.0,Female,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,NaN,Female,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,21.0,Female,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
14,Daron,Eagger,deagger1983@simpleme.org,38.0,Male,66.22
15,Liam,Pasley,lpasley26@usatoday.com,26.0,Male,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,NaN,Rather not say,210.35
17,Hans,Fischer,hansfish@hc360.com,19.0,Male,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,64.0,Female,-100.00
19,Nadine,De Smet,nadineds22@email.be,45.0,Female,4.38

inserisco un default per l'eta

In [11]:
media_eta = df4["eta"].mean()

df4["eta"] = df4["eta"].fillna(media_eta).copy()
df4

,nome,cognome,email,eta,genere,credito
0,Diana,Herries,sherries3@google.com.au,42.0,Female,58.00
1,Maira,Totaro,mtota21@salento.com,41.0,Female,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,36.0,Male,308.15
3,Ferenc,Toth,toth.f@ucla.edu,41.0,Male,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,37.0,Female,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,38.0,Female,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,41.0,Female,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,21.0,Female,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
14,Daron,Eagger,deagger1983@simpleme.org,38.0,Male,66.22
15,Liam,Pasley,lpasley26@usatoday.com,26.0,Male,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,41.0,Rather not say,210.35
17,Hans,Fischer,hansfish@hc360.com,19.0,Male,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,64.0,Female,-100.00
19,Nadine,De Smet,nadineds22@email.be,45.0,Female,4.38

elimino righe con credito < di 0

In [12]:
df5 = df4[df4["credito"] > 0].copy()
df5

,nome,cognome,email,eta,genere,credito
0,Diana,Herries,sherries3@google.com.au,42.0,Female,58.00
1,Maira,Totaro,mtota21@salento.com,41.0,Female,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,36.0,Male,308.15
3,Ferenc,Toth,toth.f@ucla.edu,41.0,Male,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,37.0,Female,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,38.0,Female,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,79.0,Male,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,41.0,Female,5.99
12,Carmen,Broadbear,cbroadbear2f@technorati.com,47.0,Female,257.40
14,Daron,Eagger,deagger1983@simpleme.org,38.0,Male,66.22
15,Liam,Pasley,lpasley26@usatoday.com,26.0,Male,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,41.0,Rather not say,210.35
17,Hans,Fischer,hansfish@hc360.com,19.0,Male,105.85
19,Nadine,De Smet,nadineds22@email.be,45.0,Female,4.38

specifico che l'indice è email:

In [17]:
if df["email"].is_unique:
    print("1")
    df6 = df5.set_index("email").copy()

In [18]:
df6 = df5.set_index("email").copy()
df6

,nome,cognome,eta,genere,credito
email,,,,,
sherries3@google.com.au,Diana,Herries,42.0,Female,58.00
mtota21@salento.com,Maira,Totaro,41.0,Female,38.60
pgillardi@toplist.ch,Patrice,Gillard,36.0,Male,308.15
toth.f@ucla.edu,Ferenc,Toth,41.0,Male,362.20
svdeer@indiatimes.com,Sonja,Van Deer,37.0,Female,88.00
c.diaz.12@elpais.com,Carolina,Diaz,38.0,Female,19.99
bakshi.a@unesco.org,Akshay,Bakshi,79.0,Male,20.48
glammas-11@fda.gov,Geraldine,Lammas,41.0,Female,5.99
cbroadbear2f@technorati.com,Carmen,Broadbear,47.0,Female,257.40
deagger1983@simpleme.org,Daron,Eagger,38.0,Male,66.22
lpasley26@usatoday.com,Liam,Pasley,26.0,Male,138.58
rkeilloh27@unesco.org,Rey,Keilloh,41.0,Rather not say,210.35
hansfish@hc360.com,Hans,Fischer,19.0,Male,105.85
nadineds22@email.be,Nadine,De Smet,45.0,Female,4.38

In [19]:
df6.to_csv("ml-output.csv", index=True)

carico specificando l'indice

In [20]:
df10 = pd.read_csv("ml-output.csv", index_col="email")

In [21]:
df10

,nome,cognome,eta,genere,credito
email,,,,,
sherries3@google.com.au,Diana,Herries,42.0,Female,58.00
mtota21@salento.com,Maira,Totaro,41.0,Female,38.60
pgillardi@toplist.ch,Patrice,Gillard,36.0,Male,308.15
toth.f@ucla.edu,Ferenc,Toth,41.0,Male,362.20
svdeer@indiatimes.com,Sonja,Van Deer,37.0,Female,88.00
c.diaz.12@elpais.com,Carolina,Diaz,38.0,Female,19.99
bakshi.a@unesco.org,Akshay,Bakshi,79.0,Male,20.48
glammas-11@fda.gov,Geraldine,Lammas,41.0,Female,5.99
cbroadbear2f@technorati.com,Carmen,Broadbear,47.0,Female,257.40
deagger1983@simpleme.org,Daron,Eagger,38.0,Male,66.22
lpasley26@usatoday.com,Liam,Pasley,26.0,Male,138.58
rkeilloh27@unesco.org,Rey,Keilloh,41.0,Rather not say,210.35
hansfish@hc360.com,Hans,Fischer,19.0,Male,105.85
nadineds22@email.be,Nadine,De Smet,45.0,Female,4.38

## visualizzazione con grafici

In [22]:
%pip install ydata_profiling

Collecting ydata_profiling
  Using cached ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (3.9.2)
Requirement already satisfied: pydantic<3,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (2.8.2)
Collecting PyYAML<6.1,>=6.0.3 (from ydata_profiling)
  Using cached pyyaml-6.0.3-cp312-cp312-macosx_10_13_x86_64.whl.metadata (2.4 kB)
Collecting jinja2<3.2,>=3.1.6 (from ydata_profiling)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Using cached visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (1.26.4)
Collecting minify-html>=0.15.0 (from ydata_profiling)
  Using cached minify_html-0.18.1-cp312-cp312-macosx_10_12_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata_profiling)
  Using cached filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata_profiling)
  Using cached phik-0.12.5-cp312-cp312-macosx_10_13_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (4.66.5)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata_profiling)
  Using cached multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (0.14.2)
Collecting typeguard<5,>=4 (from ydata_profiling)
  Using cached typeguard-4.4.4-py3-none-any.whl.metadata (3.3 kB)
Collecting imagehash==4.3.2 (from ydata_profiling)
  Using cached ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata_profiling)
  Using cached wordcloud-1.9.6-cp312-cp312-macosx_10_13_x86_64.whl.metadata (3.4 kB)
Collecting dacite<2,>=1.9 (from ydata_profiling)
  Using cached dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /opt/anaconda3/lib/python3.12/site-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /opt/anaconda3/lib/python3.12/site-packages (from imagehash==4.3.2->ydata_profiling) (1.7.0)
Requirement already satisfied: pillow in /opt/anaconda3/lib/python3.12/site-packages (from imagehash==4.3.2->ydata_profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2<3.2,>=3.1.6->ydata_profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /opt/anaconda3/lib/python3.12/site-packages (from numba<0.63,>=0.60->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /opt/anaconda3/lib/python3.12/site-packages (from phik<0.13,>=0.12.5->ydata_profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=2->ydata_profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=2->ydata_profiling) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=2->ydata_profiling) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata_profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata_profiling) (2024.12.14)
Requirement already satisfied: patsy>=0.5.6 in /opt/anaconda3/lib/python3.12/site-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (0.5.6)
Collecting typing-extensions>=4.6.1 (from pydantic<3,>=2->ydata_profiling)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: attrs>=19.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /opt/anaconda3/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.3)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Using cached puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata_profiling) (1.16.0)
Using cached ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
Using cached ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Using cached dacite-1.9.2-py3-none-any.whl (16 kB)
Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached minify_html-0.18.1-cp312-cp312-macosx_10_12_x86_64.whl (3.1 MB)
Using cached multimethod-1.12-py3-none-any.whl (10 kB)
Using cached phik-0.12.5-cp312-cp312-macosx_10_13_x86_64.whl (671 kB)
Using cached pyyaml-6.0.3-cp312-cp312-macosx_10_13_x86_64.whl (182 kB)
Using cached typeguard-4.4.4-py3-none-any.whl (34 kB)
Using cached visions-0.8.1-py3-none-any.whl (105 kB)
Using cached wordcloud-1.9.6-cp312-cp312-macosx_10_13_x86_64.whl (170 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached puremagic-1.30-py3-none-any.whl (43 kB)
Installing collected packages: puremagic, minify-html, filetype, typing-extensions, PyYAML, multimethod, jinja2, dacite, typeguard, imagehash, wordcloud, visions, phik, ydata_profiling
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.11.0
    Uninstalling typing_extensions-4.11.0:
      Successfully uninstalled typing_extensions-4.11.0
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.1
    Uninstalling PyYAML-6.0.1:
      Successfully uninstalled PyYAML-6.0.1
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.4
    Uninstalling Jinja2-3.1.4:
      Successfully uninstalled Jinja2-3.1.4
Successfully installed PyYAML-6.0.3 dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 jinja2-3.1.6 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-1.30 typeguard-4.4.4 typing-extensions-4.15.0 visions-0.8.1 wordcloud-1.9.6 ydata_profiling-4.18.1
Note: you may need to restart the kernel to use updated packages.

In [26]:
import pandas as pd
from ydata_profiling import ProfileReport  # pandas_profiling ora è ydata-profiling

df11 = pd.read_csv("ml-output.csv")

profile = ProfileReport(df11, title="Report Dataset", explorative=True)
#profile.to_widgets()       # visualizza direttamente nel notebook
# oppure 
profile.to_file("report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 17734.90it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]