## Pandas - Merge e Join

In [1]:
import pandas as pd

In [2]:
#genero un dataframe con un dict
data = {"codice":range(1001, 1006), 'nome':["mela","pera","kiwi","banana","fragola"]}
df1 = pd.DataFrame(data)
df1

   codice     nome
0    1001     mela
1    1002     pera
2    1003     kiwi
3    1004   banana
4    1005  fragola

In [3]:
#genero una seconda tabella con le qta
data = {"codice":range(1001, 1011), 'qta':[10,20,30,40,12,22,44,55,66,77]}
df2 = pd.DataFrame(data)
df2

   codice  qta
0    1001   10
1    1002   20
2    1003   30
3    1004   40
4    1005   12
5    1006   22
6    1007   44
7    1008   55
8    1009   66
9    1010   77

In [4]:
#unisco le due tabelle
df3 = pd.merge(df1, df2, on="codice", how="left")
df3

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003     kiwi   30
3    1004   banana   40
4    1005  fragola   12

In [5]:
df3 = pd.merge(df1, df2, on="codice", how="right")
df3

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003     kiwi   30
3    1004   banana   40
4    1005  fragola   12
5    1006      NaN   22
6    1007      NaN   44
7    1008      NaN   55
8    1009      NaN   66
9    1010      NaN   77

In [6]:
#aggiungo una riga a df1
df1.loc[5] = {"codice":1100, "nome":"fichi"}
df1

   codice     nome
0    1001     mela
1    1002     pera
2    1003     kiwi
3    1004   banana
4    1005  fragola
5    1100    fichi

In [7]:
df3 = pd.merge(df1, df2, on="codice", how="right")
df3

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003     kiwi   30
3    1004   banana   40
4    1005  fragola   12
5    1006      NaN   22
6    1007      NaN   44
7    1008      NaN   55
8    1009      NaN   66
9    1010      NaN   77

In [8]:
df3 = pd.merge(df1, df2, on="codice", how="inner")
df3

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003     kiwi   30
3    1004   banana   40
4    1005  fragola   12

In [9]:
df3 = pd.merge(df1, df2, on="codice", how="outer")
df3

    codice     nome   qta
0     1001     mela  10.0
1     1002     pera  20.0
2     1003     kiwi  30.0
3     1004   banana  40.0
4     1005  fragola  12.0
5     1006      NaN  22.0
6     1007      NaN  44.0
7     1008      NaN  55.0
8     1009      NaN  66.0
9     1010      NaN  77.0
10    1100    fichi   NaN

### Concat
Unire due dataframe con struttura compatibile

In [10]:
data = {
    "codice":[10,20,30],
    "nome":["mela", "pera", "kiwi"],
    "qta":[100, 87, 45]
}
dfa = pd.DataFrame(data)
dfa

   codice  nome  qta
0      10  mela  100
1      20  pera   87
2      30  kiwi   45

In [11]:
data = {
    "codice":[100, 200],
    "nome":["patate", "sedano"],
    "qta":[33,45]
}
dfb = pd.DataFrame(data)
dfb

   codice    nome  qta
0     100  patate   33
1     200  sedano   45

In [13]:
dfc = pd.concat([dfa, dfb], ignore_index=True)
dfc

   codice    nome  qta
0      10    mela  100
1      20    pera   87
2      30    kiwi   45
3     100  patate   33
4     200  sedano   45

In [14]:
dfd = pd.concat([dfa, dfb])
dfd

   codice    nome  qta
0      10    mela  100
1      20    pera   87
2      30    kiwi   45
0     100  patate   33
1     200  sedano   45

In [15]:
dfd.reset_index(drop=True, inplace=True)
dfd

   codice    nome  qta
0      10    mela  100
1      20    pera   87
2      30    kiwi   45
3     100  patate   33
4     200  sedano   45