## Pandas - Join/merge

Le join di tabelle si fanno con merge che prende come tipo di join: outer, inner , left e right

In [1]:
import pandas as pd

In [2]:
data = {
    'codice':range(1001, 1006),
    'nome':['mela', 'pera', 'banana', 'kiwi', 'fragola']
}
df_prodotti = pd.DataFrame(data)
df_prodotti

   codice     nome
0    1001     mela
1    1002     pera
2    1003   banana
3    1004     kiwi
4    1005  fragola

In [3]:
data = {
    'codice':range(1001, 1011),
    'qta':[10,20,30,40,50,60,70,80,90,99]
}
df_magazzino = pd.DataFrame(data)
df_magazzino

   codice  qta
0    1001   10
1    1002   20
2    1003   30
3    1004   40
4    1005   50
5    1006   60
6    1007   70
7    1008   80
8    1009   90
9    1010   99

In [4]:
df1 = pd.merge(df_prodotti, df_magazzino, on="codice", how="left")
df1

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003   banana   30
3    1004     kiwi   40
4    1005  fragola   50

In [5]:
df2 = pd.merge(df_prodotti, df_magazzino, on="codice", how="right")
df2

   codice     nome  qta
0    1001     mela   10
1    1002     pera   20
2    1003   banana   30
3    1004     kiwi   40
4    1005  fragola   50
5    1006      NaN   60
6    1007      NaN   70
7    1008      NaN   80
8    1009      NaN   90
9    1010      NaN   99

## concat
Unire due dataframe con la stessa forma (numero e tipo di colonne)

In [6]:
data = {
    'codice':[10,20,30],
    'nome':['kiwi', 'banana', 'fragola'],
    'qta':[100,50,77]
}
dfa = pd.DataFrame(data)
dfa

   codice     nome  qta
0      10     kiwi  100
1      20   banana   50
2      30  fragola   77

In [7]:
data = {
    'codice':[40,50],
    'nome':['patate', 'carote'],
    'qta':[55,66]
}
dfb = pd.DataFrame(data)
dfb

   codice    nome  qta
0      40  patate   55
1      50  carote   66

In [9]:
dfc = pd.concat([dfa, dfb], ignore_index= True)
dfc

   codice     nome  qta
0      10     kiwi  100
1      20   banana   50
2      30  fragola   77
3      40   patate   55
4      50   carote   66

## Raggruppamenti - GroupBy

In [11]:
data = {
    'codice':[10,20,30,40, 50, 60],
    'nome':['kiwi', 'banana', 'fragola', 'mela', 'pera', 'ananas'],
    'qta':[100,50,77,23,34,45],
    'mag':[1,1,0,0,1,0]
}
dfp = pd.DataFrame(data)
dfp

   codice     nome  qta  mag
0      10     kiwi  100    1
1      20   banana   50    1
2      30  fragola   77    0
3      40     mela   23    0
4      50     pera   34    1
5      60   ananas   45    0

In [12]:
dfp.groupby('mag').groups

{0: [2, 3, 5], 1: [0, 1, 4]}

In [13]:
dfp.groupby("mag").get_group(0)

   codice     nome  qta  mag
2      30  fragola   77    0
3      40     mela   23    0
5      60   ananas   45    0

In [14]:
dfp.groupby("mag")['qta'].sum()

mag
0    145
1    184
Name: qta, dtype: int64

In [15]:
dfp.groupby("mag")['qta'].describe()

     count       mean        std   min   25%   50%   75%    max
mag
0      3.0  48.333333  27.153882  23.0  34.0  45.0  61.0   77.0
1      3.0  61.333333  34.428670  34.0  42.0  50.0  75.0  100.0