### Workflow elaborazione mailing list

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("dati_mailing_list.csv", delimiter=",")
df.head(3)

,First name,Surname,__Email_Entered,Gender,Age,Logins,_CREDIT,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First name       20 non-null     object
 1   Surname          20 non-null     object
 2   __Email_Entered  20 non-null     object
 3   Gender           20 non-null     object
 4   Age              16 non-null     float64
 5   Logins           16 non-null     float64
 6   _CREDIT          20 non-null     float64
 7   IP_Address       20 non-null     object
dtypes: float64(3), object(5)
memory usage: 1.4+ KB

In [11]:
df.describe()

             Age     Logins     _CREDIT
count  16.000000  16.000000   20.000000
mean   43.375000   2.812500  104.281000
std    18.463929   1.424488  127.852396
min    19.000000   1.000000 -100.000000
25%    33.500000   1.750000   20.357500
50%    40.000000   3.000000   77.110000
75%    48.750000   3.250000  208.040000
max    79.000000   5.000000  362.200000

In [12]:
df.dtypes

First name          object
Surname             object
__Email_Entered     object
Gender              object
Age                float64
Logins             float64
_CREDIT            float64
IP_Address          object
dtype: object

Rinomino le colonne

In [13]:
df.rename(columns={'First name':"nome"}, inplace=True)
df.head(3)

,nome,Surname,__Email_Entered,Gender,Age,Logins,_CREDIT,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20

In [16]:
df.rename(columns={'Surname':"cognome", "__Email_Entered":"email"}, inplace=True)
df.rename(columns={'Gender':"genere", "Age":"eta", "_CREDIT":"credito"}, inplace=True)
df

,nome,cognome,email,genere,eta,Logins,credito,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74
5,Carolina,DIAZ,c.diaz.12@elpais.com,Female,38.0,2.0,19.99,60.92.1.255
6,Ruby,Mammatt,rmammatt16@prweb,Rather not say,22.0,NaN,116.28,97.250.180.101
7,AKSHAY,BAKSHI,bakshi.a@unesco.org,Male,79.0,5.0,20.48,54.14.129.156
8,AKSHAY,BAKSHI,bakshi.a@unesco.org,Male,79.0,5.0,20.48,54.14.129.156
9,geraldine,lammas,glammas-11@fda.gov,Female,NaN,1.0,5.99,17.85.250.10
10,Jacek,WLOSKI,jacekwlochem.com,Male,54.0,4.0,207.27,124.194.190.254
11,Nichole,De Giovanni,ndegio@ifeng.com,Female,21.0,5.0,-100.00,154.95.98.49
12,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47.0,3.0,257.40,238.166.197.131
13,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47.0,3.0,257.40,238.166.197.131
14,Daron,eagger,deagger1983@simpleme.org,Male,38.0,NaN,66.22,220.224.22.202
15,Liam,Pasley,lpasley26@usatoday.com,Male,26.0,3.0,138.58,155.109.75.175
16,rey,KEILLOH,rkeilloh27@unesco.org,Rather not say,NaN,3.0,210.35,10.241.133.157
17,Hans,Fischer,hansfish@hc360.com,Male,19.0,3.0,105.85,42.173.14.160
18,Beckie,Swindell,bswindell29@google.co.uk,Female,64.0,1.0,-100.00,33.154.178.139
19,Nadine,De Smet,nadineds22@email.be,Female,45.0,1.0,4.38,42.26.246.106

In [17]:
#elimino le colonne che non mi interessano
df.drop("Logins", axis=1, inplace=True)
df.head(3)

,nome,cognome,email,genere,eta,credito,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,308.15,110.182.242.20

In [18]:
df.drop("IP_Address", axis=1, inplace=True)
df.head(3)

        nome  cognome                    email  genere   eta  credito
0      DIANA  Herries  sherries3@google.com.au  Female  42.0    58.00
1      Maira   Totaro      mtota21@salento.com  Female   NaN    38.60
2    Patrice  Gillard     pgillardi@toplist.ch    Male  36.0   308.15

In [19]:
#elimino gli spazi vuoti dalle colonne
df["nome"] = df["nome"].str.strip() #toglie gli spazi vuoti
df["nome"] = df["nome"].str.title() #mette l'iniziale maiuscola
df.head(3)

      nome  cognome                    email  genere   eta  credito
0    Diana  Herries  sherries3@google.com.au  Female  42.0    58.00
1    Maira   Totaro      mtota21@salento.com  Female   NaN    38.60
2  Patrice  Gillard     pgillardi@toplist.ch    Male  36.0   308.15

In [20]:
df["cognome"] = df["cognome"].str.strip()
df["cognome"] = df["cognome"].str.title()
df.head(3)

      nome  cognome                    email  genere   eta  credito
0    Diana  Herries  sherries3@google.com.au  Female  42.0    58.00
1    Maira   Totaro      mtota21@salento.com  Female   NaN    38.60
2  Patrice  Gillard     pgillardi@toplist.ch    Male  36.0   308.15

In [22]:
#elimino le email non valide
import re
email_re = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
df2 = df[ df["email"].str.match(email_re, na=False) ]
df2

,nome,cognome,email,genere,eta,credito
0,Diana,Herries,sherries3@google.com.au,Female,42.0,58.00
1,Maira,Totaro,mtota21@salento.com,Female,NaN,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,308.15
3,Ferenc,Toth,toth.f@ucla.edu,Male,NaN,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,Female,37.0,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,Female,38.0,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,Male,79.0,20.48
8,Akshay,Bakshi,bakshi.a@unesco.org,Male,79.0,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,Female,NaN,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,Female,21.0,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47.0,257.40
13,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47.0,257.40
14,Daron,Eagger,deagger1983@simpleme.org,Male,38.0,66.22
15,Liam,Pasley,lpasley26@usatoday.com,Male,26.0,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,Rather not say,NaN,210.35
17,Hans,Fischer,hansfish@hc360.com,Male,19.0,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,Female,64.0,-100.00
19,Nadine,De Smet,nadineds22@email.be,Female,45.0,4.38

In [ ]:
#righe doppie
#stampo il numero di righe doppie
df2.duplicated(subset=["email"]).sum()

#se vuoto considera tutti i campi
#df2.duplicated().sum()

2

In [ ]:
df3 = df2.drop_duplicates( subset=["email"], keep="first" ).copy()
df3

,nome,cognome,email,genere,eta,credito
0,Diana,Herries,sherries3@google.com.au,Female,42.0,58.00
1,Maira,Totaro,mtota21@salento.com,Female,NaN,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,308.15
3,Ferenc,Toth,toth.f@ucla.edu,Male,NaN,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,Female,37.0,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,Female,38.0,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,Male,79.0,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,Female,NaN,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,Female,21.0,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47.0,257.40
14,Daron,Eagger,deagger1983@simpleme.org,Male,38.0,66.22
15,Liam,Pasley,lpasley26@usatoday.com,Male,26.0,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,Rather not say,NaN,210.35
17,Hans,Fischer,hansfish@hc360.com,Male,19.0,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,Female,64.0,-100.00
19,Nadine,De Smet,nadineds22@email.be,Female,45.0,4.38

In [29]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 19
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     16 non-null     object
 1   cognome  16 non-null     object
 2   email    16 non-null     object
 3   genere   16 non-null     object
 4   eta      12 non-null     float64
 5   credito  16 non-null     float64
dtypes: float64(2), object(4)
memory usage: 896.0+ bytes

In [30]:
#inserisco il valore medio dove manca
etamedia = df3["eta"].mean()
print("eta media:", etamedia)

eta media: 41.0

In [31]:
#inserisco l'eta media dove manca
df3["eta"] = df3["eta"].fillna(etamedia)
df3

C:\Users\paolo\AppData\Local\Temp\ipykernel_12660\74542612.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["eta"] = df3["eta"].fillna(etamedia)

,nome,cognome,email,genere,eta,credito
0,Diana,Herries,sherries3@google.com.au,Female,42.0,58.00
1,Maira,Totaro,mtota21@salento.com,Female,41.0,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,308.15
3,Ferenc,Toth,toth.f@ucla.edu,Male,41.0,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,Female,37.0,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,Female,38.0,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,Male,79.0,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,Female,41.0,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,Female,21.0,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47.0,257.40
14,Daron,Eagger,deagger1983@simpleme.org,Male,38.0,66.22
15,Liam,Pasley,lpasley26@usatoday.com,Male,26.0,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,Rather not say,41.0,210.35
17,Hans,Fischer,hansfish@hc360.com,Male,19.0,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,Female,64.0,-100.00
19,Nadine,De Smet,nadineds22@email.be,Female,45.0,4.38

In [32]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 19
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     16 non-null     object
 1   cognome  16 non-null     object
 2   email    16 non-null     object
 3   genere   16 non-null     object
 4   eta      16 non-null     float64
 5   credito  16 non-null     float64
dtypes: float64(2), object(4)
memory usage: 896.0+ bytes

In [33]:
#trasformo il tipo di dato della colonna eta in un intero
df3["eta"] = df3["eta"].round(0).astype(int)  #round(0) toglie le virgole - astype(int) trasforma in int
df3

C:\Users\paolo\AppData\Local\Temp\ipykernel_12660\749341885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["eta"] = df3["eta"].round(0).astype(int)  #round(0) toglie le virgole - astype(int) trasforma in int

,nome,cognome,email,genere,eta,credito
0,Diana,Herries,sherries3@google.com.au,Female,42,58.00
1,Maira,Totaro,mtota21@salento.com,Female,41,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36,308.15
3,Ferenc,Toth,toth.f@ucla.edu,Male,41,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,Female,37,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,Female,38,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,Male,79,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,Female,41,5.99
11,Nichole,De Giovanni,ndegio@ifeng.com,Female,21,-100.00
12,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47,257.40
14,Daron,Eagger,deagger1983@simpleme.org,Male,38,66.22
15,Liam,Pasley,lpasley26@usatoday.com,Male,26,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,Rather not say,41,210.35
17,Hans,Fischer,hansfish@hc360.com,Male,19,105.85
18,Beckie,Swindell,bswindell29@google.co.uk,Female,64,-100.00
19,Nadine,De Smet,nadineds22@email.be,Female,45,4.38

In [34]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 19
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     16 non-null     object
 1   cognome  16 non-null     object
 2   email    16 non-null     object
 3   genere   16 non-null     object
 4   eta      16 non-null     int32
 5   credito  16 non-null     float64
dtypes: float64(1), int32(1), object(4)
memory usage: 832.0+ bytes

In [35]:
#elimino righe con credito < 0
df4 = df3[ df3["credito"] > 0 ]
df4

,nome,cognome,email,genere,eta,credito
0,Diana,Herries,sherries3@google.com.au,Female,42,58.00
1,Maira,Totaro,mtota21@salento.com,Female,41,38.60
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36,308.15
3,Ferenc,Toth,toth.f@ucla.edu,Male,41,362.20
4,Sonja,Van Deer,svdeer@indiatimes.com,Female,37,88.00
5,Carolina,Diaz,c.diaz.12@elpais.com,Female,38,19.99
7,Akshay,Bakshi,bakshi.a@unesco.org,Male,79,20.48
9,Geraldine,Lammas,glammas-11@fda.gov,Female,41,5.99
12,Carmen,Broadbear,cbroadbear2f@technorati.com,Female,47,257.40
14,Daron,Eagger,deagger1983@simpleme.org,Male,38,66.22
15,Liam,Pasley,lpasley26@usatoday.com,Male,26,138.58
16,Rey,Keilloh,rkeilloh27@unesco.org,Rather not say,41,210.35
17,Hans,Fischer,hansfish@hc360.com,Male,19,105.85
19,Nadine,De Smet,nadineds22@email.be,Female,45,4.38

In [37]:
df4.to_csv("ml_clean.csv", index=False)