## Pandas
pip install pandas

In [1]:
import pandas as pd

In [3]:
tab = pd.read_csv("persone.csv", delimiter=",")
tab.head()

       nome    cognome  peso  altezza data_nascita sesso
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
2   Bettina       Toso  93.5     1.88   1960-01-25     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M

In [5]:
tab.dtypes

nome             object
cognome          object
peso            float64
altezza         float64
data_nascita     object
sesso            object
dtype: object

In [6]:
tab.describe()

            peso    altezza
count  10.000000  10.000000
mean   76.190000   1.813000
std    14.879998   0.117289
min    54.900000   1.590000
25%    64.600000   1.792500
50%    81.650000   1.830000
75%    83.775000   1.887500
max    96.400000   1.940000

In [7]:
tab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nome          10 non-null     object
 1   cognome       10 non-null     object
 2   peso          10 non-null     float64
 3   altezza       10 non-null     float64
 4   data_nascita  10 non-null     object
 5   sesso         10 non-null     object
dtypes: float64(2), object(4)
memory usage: 612.0+ bytes

In [ ]:
t2 = tab.sort_values(by="cognome")
t2

       nome    cognome  peso  altezza data_nascita sesso
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M
8      Pier    Udinesi  55.5     1.89   1993-05-15     M

In [9]:
t3 = t2[["cognome", "nome"]]
t3

     cognome      nome
1  Barillaro  Giovanni
3    Bettoni     Carlo
4   Bompiani     Mauro
7  Gagliardi      Tina
5    Galuppi   Gustavo
6    Tartini    Puccio
2       Toso   Bettina
0  Trapanese  Giacobbe
9     Turchi  Alderano
8    Udinesi      Pier

In [10]:
t2

       nome    cognome  peso  altezza data_nascita sesso
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M
8      Pier    Udinesi  55.5     1.89   1993-05-15     M

In [ ]:
t2["data_nascita"] = pd.to_datetime(t2["data_nascita"])
t2.dtypes

nome                    object
cognome                 object
peso                   float64
altezza                float64
data_nascita    datetime64[ns]
sesso                   object
dtype: object

In [17]:
def f1(x):
    #operatore ternario - if su una riga sola
    return "MALE" if (x == "M") else "FEMALE"
    #if x == "M":
    #    return "MALE"
    #else:
    #    return "FEMALE"

t2["genere"] = t2["sesso"].apply(f1)
t2["genere2"] = t2["sesso"].apply(lambda x : ("MALE" if (x == "M") else "FEMALE"))
t2.head()

       nome    cognome  peso  altezza data_nascita sesso  genere genere2
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F  FEMALE  FEMALE
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F  FEMALE  FEMALE
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M    MALE    MALE
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F  FEMALE  FEMALE
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M    MALE    MALE

**Indici e posizioni**

loc richiama una riga usando la "chiave"

In [22]:
r = t2.loc[0]
print(r["nome"])
r

Giacobbe

nome                       Giacobbe
cognome                   Trapanese
peso                           63.6
altezza                        1.94
data_nascita    1971-12-26 00:00:00
sesso                             M
genere                         MALE
genere2                        MALE
Name: 0, dtype: object

Estraggo una riga usando la posizione

uso iloc

In [23]:
t2.head()

       nome    cognome  peso  altezza data_nascita sesso  genere genere2
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F  FEMALE  FEMALE
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F  FEMALE  FEMALE
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M    MALE    MALE
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F  FEMALE  FEMALE
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M    MALE    MALE

In [24]:
t2.iloc[0]

nome                       Giovanni
cognome                   Barillaro
peso                           84.0
altezza                         1.8
data_nascita    1984-08-10 00:00:00
sesso                             F
genere                       FEMALE
genere2                      FEMALE
Name: 1, dtype: object