## Workflow Ripulitura Mailing List CSV

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dati_mailing_list.csv", delimiter=",")
df.head()

,First name,Surname,__Email_Entered,Gender,Age,Logins,_CREDIT,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74

Esploro i dati nel file usando info, describe, dtype, hist...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First name       20 non-null     object
 1   Surname          20 non-null     object
 2   __Email_Entered  20 non-null     object
 3   Gender           20 non-null     object
 4   Age              16 non-null     float64
 5   Logins           16 non-null     float64
 6   _CREDIT          20 non-null     float64
 7   IP_Address       20 non-null     object
dtypes: float64(3), object(5)
memory usage: 1.4+ KB

In [5]:
df.describe()

             Age     Logins     _CREDIT
count  16.000000  16.000000   20.000000
mean   43.375000   2.812500  104.281000
std    18.463929   1.424488  127.852396
min    19.000000   1.000000 -100.000000
25%    33.500000   1.750000   20.357500
50%    40.000000   3.000000   77.110000
75%    48.750000   3.250000  208.040000
max    79.000000   5.000000  362.200000

In [6]:
df.dtypes

First name          object
Surname             object
__Email_Entered     object
Gender              object
Age                float64
Logins             float64
_CREDIT            float64
IP_Address          object
dtype: object

Modifico i nomi delle colonne

In [9]:
df = df.rename(columns={"__Email_Entered":"email"})
df.head()

,First name,Surname,email,Gender,Age,Logins,_CREDIT,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74

In [11]:
df.rename(columns={"First name":"nome"}, inplace=True)
df.head()

,nome,Surname,email,Gender,Age,Logins,_CREDIT,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74

In [15]:
df.rename(columns={"Surname":"cognome", "Gender":"sesso", "Age":"eta", "_CREDIT":"credito"}, inplace=True)
df.head()

,nome,cognome,email,sesso,eta,Logins,credit,IP_Address
0,DIANA,Herries,sherries3@google.com.au,Female,42.0,3.0,58.00,162.53.211.57
1,Maira,Totaro,mtota21@salento.com,Female,NaN,2.0,38.60,50.250.21.116
2,Patrice,Gillard,pgillardi@toplist.ch,Male,36.0,NaN,308.15,110.182.242.20
3,Ferenc,TOTH,toth.f@ucla.edu,Male,NaN,1.0,362.20,192.81.246.91
4,SONJA,VAN DEER,svdeer@indiatimes.com,Female,37.0,NaN,88.00,166.194.37.74

Devo eliminare le colonne Logins e IP_Address. Posso dare un drop (axis=1), oppure seleziono le colonne che voglio tenere. In pratica creo una sotto-tabella

In [20]:
df2 = df[["email", "nome", "cognome", "sesso", "eta", "credit"]].copy()
df2.head()

                     email       nome     cognome   sesso   eta  credit
0  sherries3@google.com.au      DIANA     Herries  Female  42.0   58.00
1      mtota21@salento.com      Maira      Totaro  Female   NaN   38.60
2     pgillardi@toplist.ch    Patrice     Gillard    Male  36.0  308.15
3          toth.f@ucla.edu     Ferenc       TOTH     Male   NaN  362.20
4    svdeer@indiatimes.com      SONJA    VAN DEER  Female  37.0   88.00

Ora rimuovo gli spazi in eccesso (strip()) nelle colonne "nome" e "cognome"

In [22]:
df2["nome"] = df2["nome"].str.strip()
df2["nome"] = df2["nome"].str.title()
df2.head()

                     email     nome     cognome   sesso   eta  credit
0  sherries3@google.com.au    Diana     Herries  Female  42.0   58.00
1      mtota21@salento.com    Maira      Totaro  Female   NaN   38.60
2     pgillardi@toplist.ch  Patrice     Gillard    Male  36.0  308.15
3          toth.f@ucla.edu   Ferenc       TOTH     Male   NaN  362.20
4    svdeer@indiatimes.com    Sonja    VAN DEER  Female  37.0   88.00

In [23]:
df2["cognome"] = df2["cognome"].str.strip().str.title()
df2.head()

                     email     nome   cognome   sesso   eta  credit
0  sherries3@google.com.au    Diana   Herries  Female  42.0   58.00
1      mtota21@salento.com    Maira    Totaro  Female   NaN   38.60
2     pgillardi@toplist.ch  Patrice   Gillard    Male  36.0  308.15
3          toth.f@ucla.edu   Ferenc      Toth    Male   NaN  362.20
4    svdeer@indiatimes.com    Sonja  Van Deer  Female  37.0   88.00

Elimino le email non valide usando una RegExp.

In [24]:
import re
email_re = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

In [27]:
df3 = df2[ df2["email"].str.match(email_re, na=False) ].copy()
df3

,email,nome,cognome,sesso,eta,credit
0,sherries3@google.com.au,Diana,Herries,Female,42.0,58.00
1,mtota21@salento.com,Maira,Totaro,Female,NaN,38.60
2,pgillardi@toplist.ch,Patrice,Gillard,Male,36.0,308.15
3,toth.f@ucla.edu,Ferenc,Toth,Male,NaN,362.20
4,svdeer@indiatimes.com,Sonja,Van Deer,Female,37.0,88.00
5,c.diaz.12@elpais.com,Carolina,Diaz,Female,38.0,19.99
7,bakshi.a@unesco.org,Akshay,Bakshi,Male,79.0,20.48
8,bakshi.a@unesco.org,Akshay,Bakshi,Male,79.0,20.48
9,glammas-11@fda.gov,Geraldine,Lammas,Female,NaN,5.99
11,ndegio@ifeng.com,Nichole,De Giovanni,Female,21.0,-100.00
12,cbroadbear2f@technorati.com,Carmen,Broadbear,Female,47.0,257.40
13,cbroadbear2f@technorati.com,Carmen,Broadbear,Female,47.0,257.40
14,deagger1983@simpleme.org,Daron,Eagger,Male,38.0,66.22
15,lpasley26@usatoday.com,Liam,Pasley,Male,26.0,138.58
16,rkeilloh27@unesco.org,Rey,Keilloh,Rather not say,NaN,210.35
17,hansfish@hc360.com,Hans,Fischer,Male,19.0,105.85
18,bswindell29@google.co.uk,Beckie,Swindell,Female,64.0,-100.00
19,nadineds22@email.be,Nadine,De Smet,Female,45.0,4.38

Elimino le righe duplicate

In [29]:
df3.duplicated().sum()

2

In [31]:
df4 = df3.drop_duplicates(subset=["email"], keep="first").copy()
df4.head()

                     email     nome   cognome   sesso   eta  credit
0  sherries3@google.com.au    Diana   Herries  Female  42.0   58.00
1      mtota21@salento.com    Maira    Totaro  Female   NaN   38.60
2     pgillardi@toplist.ch  Patrice   Gillard    Male  36.0  308.15
3          toth.f@ucla.edu   Ferenc      Toth    Male   NaN  362.20
4    svdeer@indiatimes.com    Sonja  Van Deer  Female  37.0   88.00

Tratto le colonne con i dati mancanti.

In [33]:
#1. calcolo l'eta media
etamedia = df4["eta"].mean()
print(etamedia)

#2. inserisco il valore solo dove manca
df4["eta"] = df4["eta"].fillna(etamedia)
df4.head()

41.0

                     email     nome   cognome   sesso   eta  credit
0  sherries3@google.com.au    Diana   Herries  Female  42.0   58.00
1      mtota21@salento.com    Maira    Totaro  Female  41.0   38.60
2     pgillardi@toplist.ch  Patrice   Gillard    Male  36.0  308.15
3          toth.f@ucla.edu   Ferenc      Toth    Male  41.0  362.20
4    svdeer@indiatimes.com    Sonja  Van Deer  Female  37.0   88.00

In [34]:
df4["eta"] = df4["eta"].round(0).astype(int)
df4

,email,nome,cognome,sesso,eta,credit
0,sherries3@google.com.au,Diana,Herries,Female,42,58.00
1,mtota21@salento.com,Maira,Totaro,Female,41,38.60
2,pgillardi@toplist.ch,Patrice,Gillard,Male,36,308.15
3,toth.f@ucla.edu,Ferenc,Toth,Male,41,362.20
4,svdeer@indiatimes.com,Sonja,Van Deer,Female,37,88.00
5,c.diaz.12@elpais.com,Carolina,Diaz,Female,38,19.99
7,bakshi.a@unesco.org,Akshay,Bakshi,Male,79,20.48
9,glammas-11@fda.gov,Geraldine,Lammas,Female,41,5.99
11,ndegio@ifeng.com,Nichole,De Giovanni,Female,21,-100.00
12,cbroadbear2f@technorati.com,Carmen,Broadbear,Female,47,257.40
14,deagger1983@simpleme.org,Daron,Eagger,Male,38,66.22
15,lpasley26@usatoday.com,Liam,Pasley,Male,26,138.58
16,rkeilloh27@unesco.org,Rey,Keilloh,Rather not say,41,210.35
17,hansfish@hc360.com,Hans,Fischer,Male,19,105.85
18,bswindell29@google.co.uk,Beckie,Swindell,Female,64,-100.00
19,nadineds22@email.be,Nadine,De Smet,Female,45,4.38

In [35]:
df4.dtypes

email       object
nome        object
cognome     object
sesso       object
eta          int32
credit     float64
dtype: object

Seleziono le righe con credito > 0

In [36]:
df5 = df4[ df4["credit"] > 0 ]
df5

,email,nome,cognome,sesso,eta,credit
0,sherries3@google.com.au,Diana,Herries,Female,42,58.00
1,mtota21@salento.com,Maira,Totaro,Female,41,38.60
2,pgillardi@toplist.ch,Patrice,Gillard,Male,36,308.15
3,toth.f@ucla.edu,Ferenc,Toth,Male,41,362.20
4,svdeer@indiatimes.com,Sonja,Van Deer,Female,37,88.00
5,c.diaz.12@elpais.com,Carolina,Diaz,Female,38,19.99
7,bakshi.a@unesco.org,Akshay,Bakshi,Male,79,20.48
9,glammas-11@fda.gov,Geraldine,Lammas,Female,41,5.99
12,cbroadbear2f@technorati.com,Carmen,Broadbear,Female,47,257.40
14,deagger1983@simpleme.org,Daron,Eagger,Male,38,66.22
15,lpasley26@usatoday.com,Liam,Pasley,Male,26,138.58
16,rkeilloh27@unesco.org,Rey,Keilloh,Rather not say,41,210.35
17,hansfish@hc360.com,Hans,Fischer,Male,19,105.85
19,nadineds22@email.be,Nadine,De Smet,Female,45,4.38

Salvo il file

In [37]:
df5.to_csv("ml_clean.csv", index=False)

Imposto come indice il campo email

In [38]:
df6 = df5.set_index("email")
df6

                                  nome    cognome           sesso  eta  credit
email
sherries3@google.com.au          Diana    Herries          Female   42   58.00
mtota21@salento.com              Maira     Totaro          Female   41   38.60
pgillardi@toplist.ch           Patrice    Gillard            Male   36  308.15
toth.f@ucla.edu                 Ferenc       Toth            Male   41  362.20
svdeer@indiatimes.com            Sonja   Van Deer          Female   37   88.00
c.diaz.12@elpais.com          Carolina       Diaz          Female   38   19.99
bakshi.a@unesco.org             Akshay     Bakshi            Male   79   20.48
glammas-11@fda.gov           Geraldine     Lammas          Female   41    5.99
cbroadbear2f@technorati.com     Carmen  Broadbear          Female   47  257.40
deagger1983@simpleme.org         Daron     Eagger            Male   38   66.22
lpasley26@usatoday.com            Liam     Pasley            Male   26  138.58
rkeilloh27@unesco.org              Rey    Keilloh  Rather not say   41  210.35
hansfish@hc360.com                Hans    Fischer            Male   19  105.85
nadineds22@email.be             Nadine    De Smet          Female   45    4.38

In [40]:
df7 = df[["email","cognome", "nome", "eta", "credit", "sesso"]].copy()
df7.head()

                     email     cognome       nome   eta  credit   sesso
0  sherries3@google.com.au     Herries      DIANA  42.0   58.00  Female
1      mtota21@salento.com      Totaro      Maira   NaN   38.60  Female
2     pgillardi@toplist.ch     Gillard    Patrice  36.0  308.15    Male
3          toth.f@ucla.edu       TOTH      Ferenc   NaN  362.20    Male
4    svdeer@indiatimes.com    VAN DEER      SONJA  37.0   88.00  Female