## Pandas - parte 2

Con %pip posso installare un alibreria nell'interprete corrente

In [25]:
# %pip install pandas

In [26]:
import pandas as pd

Creare dataframe

In [27]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [28]:
lista = ["mario", "luigi", "anna", "stefano"]
df = pd.DataFrame(lista)
df

         0
0    mario
1    luigi
2     anna
3  stefano

In [29]:
#rinomino una colonna
df = df.rename(columns={0:"nomi"})
df

      nomi
0    mario
1    luigi
2     anna
3  stefano

In [30]:
idx = ["01", "02", "03", "04"]
lista = ["mario", "luigi", "anna", "stefano"]
df = pd.DataFrame(data=lista, index=idx, columns=["nomi"])
df

       nomi
01    mario
02    luigi
03     anna
04  stefano

In [31]:
idx = ["01", "02", "03"]
lista = [
    ["mela", 100, 1.98],
    ["pera", 56, 2.34],
    ["kiwi", 45, 6.34]
]
colname = ["prod", "qta", "prz"]
df = pd.DataFrame(data=lista, columns=colname, index=idx)
df

    prod  qta   prz
01  mela  100  1.98
02  pera   56  2.34
03  kiwi   45  6.34

In [32]:
lista = ["mario", "luigi", "anna", "stefano"]
df = pd.DataFrame(lista, index=range(1,5))
df

         0
1    mario
2    luigi
3     anna
4  stefano

**Series**

Sono array a 1 dimensione dotati di un indice

In [33]:
s1 = pd.Series(data=["mario","luigi","anna"])
s1

0    mario
1    luigi
2     anna
dtype: object

In [34]:
d = {"a":100, "b":200, "c":235}
s2 = pd.Series(data=d)
s2

a    100
b    200
c    235
dtype: int64

## Filtrare dati di un dataframe

In [35]:
df = pd.read_csv("persone.csv", delimiter=",")
df

       nome    cognome  peso  altezza data_nascita sesso
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
2   Bettina       Toso  93.5     1.88   1960-01-25     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
8      Pier    Udinesi  55.5     1.89   1993-05-15     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M

In [36]:
df1 = df[df.sesso=='M']
df1

       nome    cognome  peso  altezza data_nascita sesso
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
8      Pier    Udinesi  55.5     1.89   1993-05-15     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M

In [37]:
df[df.sesso == 'F']

       nome    cognome  peso  altezza data_nascita sesso
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
2   Bettina       Toso  93.5     1.88   1960-01-25     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F

In [38]:
df[df.altezza > 1.80]

       nome    cognome  peso  altezza data_nascita sesso
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
8      Pier    Udinesi  55.5     1.89   1993-05-15     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M

posso combinare più espressioni di selezione usando:

* & per l'AND
* | per l'OR
* ~ per il NOT

In [40]:
df[ (df.altezza > 1.80) & (df.sesso == 'F') ]

      nome    cognome  peso  altezza data_nascita sesso
2  Bettina       Toso  93.5     1.88   1960-01-25     F
7     Tina  Gagliardi  83.1     1.84   1997-05-11     F

In [42]:
df[ (df.altezza < 1.70) | (df.altezza > 1.85)]

       nome    cognome  peso  altezza data_nascita sesso
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
8      Pier    Udinesi  55.5     1.89   1993-05-15     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M

In [44]:
df[ ~(df.nome == 'Tina')]

       nome    cognome  peso  altezza data_nascita sesso
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
2   Bettina       Toso  93.5     1.88   1960-01-25     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
8      Pier    Udinesi  55.5     1.89   1993-05-15     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M

## manipolazione di righe e colonne

In [48]:
#estraggo una riga usando la sua chiave o indice
row = df.loc[5]
#type(row)
row

nome               Gustavo
cognome            Galuppi
peso                  67.6
altezza               1.82
data_nascita    1966-07-09
sesso                    M
Name: 5, dtype: object

In [49]:
#estraggo una riga usando la sua posizione
row = df.iloc[0]
row

nome              Giacobbe
cognome          Trapanese
peso                  63.6
altezza               1.94
data_nascita    1971-12-26
sesso                    M
Name: 0, dtype: object

In [52]:
df = df.sort_values(["cognome"])
df

       nome    cognome  peso  altezza data_nascita sesso
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M
8      Pier    Udinesi  55.5     1.89   1993-05-15     M

In [53]:
row = df.iloc[0]
row

nome              Giovanni
cognome          Barillaro
peso                  84.0
altezza                1.8
data_nascita    1984-08-10
sesso                    F
Name: 1, dtype: object

In [ ]:
#modifico una riga usando l'indice/chiave
df.loc[8] = ["Pier", "Udinesi", 60.0, 1.90, "1993-05-15", 'M']
df

       nome    cognome  peso  altezza data_nascita sesso
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M
8      Pier    Udinesi  60.0     1.90   1993-05-15     M

In [56]:
df.loc[10] = ["Mario", "Rossi", 75.5, 1.76, "1999-01-01", 'M']
df

        nome    cognome  peso  altezza data_nascita sesso
1   Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3      Carlo    Bettoni  80.5     1.79   1957-04-15     F
4      Mauro   Bompiani  96.4     1.64   1990-10-18     M
7       Tina  Gagliardi  83.1     1.84   1997-05-11     F
5    Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6     Puccio    Tartini  54.9     1.59   1973-04-05     M
2    Bettina       Toso  93.5     1.88   1960-01-25     F
0   Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9   Alderano     Turchi  82.8     1.94   1962-03-03     M
8       Pier    Udinesi  60.0     1.90   1993-05-15     M
10     Mario      Rossi  75.5     1.76   1999-01-01     M

In [60]:
# modifco solo un campo di una riga
df.at[ 10, "peso"] = 90
df

        nome    cognome  peso  altezza data_nascita sesso
1   Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3      Carlo    Bettoni  80.5     1.79   1957-04-15     F
4      Mauro   Bompiani  96.4     1.64   1990-10-18     M
7       Tina  Gagliardi  83.1     1.84   1997-05-11     F
5    Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6     Puccio    Tartini  54.9     1.59   1973-04-05     M
2    Bettina       Toso  93.5     1.88   1960-01-25     F
0   Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9   Alderano     Turchi  82.8     1.94   1962-03-03     M
8       Pier    Udinesi  60.0     1.90   1993-05-15     M
10     Mario      Rossi  90.0     1.76   1999-01-01     M

In [ ]:
# modifco più campi di una riga usando l'indice 
df.loc[ 10, ["peso", "altezza"]] = [91, 1.77]
df

        nome    cognome  peso  altezza data_nascita sesso
1   Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3      Carlo    Bettoni  80.5     1.79   1957-04-15     F
4      Mauro   Bompiani  96.4     1.64   1990-10-18     M
7       Tina  Gagliardi  83.1     1.84   1997-05-11     F
5    Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6     Puccio    Tartini  54.9     1.59   1973-04-05     M
2    Bettina       Toso  93.5     1.88   1960-01-25     F
0   Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9   Alderano     Turchi  82.8     1.94   1962-03-03     M
8       Pier    Udinesi  60.0     1.90   1993-05-15     M
10     Mario      Rossi  91.0     1.77   1999-01-01     M

In [63]:
#Elimino una riga
df.drop(10)

       nome    cognome  peso  altezza data_nascita sesso
1  Giovanni  Barillaro  84.0     1.80   1984-08-10     F
3     Carlo    Bettoni  80.5     1.79   1957-04-15     F
4     Mauro   Bompiani  96.4     1.64   1990-10-18     M
7      Tina  Gagliardi  83.1     1.84   1997-05-11     F
5   Gustavo    Galuppi  67.6     1.82   1966-07-09     M
6    Puccio    Tartini  54.9     1.59   1973-04-05     M
2   Bettina       Toso  93.5     1.88   1960-01-25     F
0  Giacobbe  Trapanese  63.6     1.94   1971-12-26     M
9  Alderano     Turchi  82.8     1.94   1962-03-03     M
8      Pier    Udinesi  60.0     1.90   1993-05-15     M

In [64]:
df.drop("data_nascita", axis=1)

        nome    cognome  peso  altezza sesso
1   Giovanni  Barillaro  84.0     1.80     F
3      Carlo    Bettoni  80.5     1.79     F
4      Mauro   Bompiani  96.4     1.64     M
7       Tina  Gagliardi  83.1     1.84     F
5    Gustavo    Galuppi  67.6     1.82     M
6     Puccio    Tartini  54.9     1.59     M
2    Bettina       Toso  93.5     1.88     F
0   Giacobbe  Trapanese  63.6     1.94     M
9   Alderano     Turchi  82.8     1.94     M
8       Pier    Udinesi  60.0     1.90     M
10     Mario      Rossi  91.0     1.77     M